
### hello
GET {{BASE_URL}}/api/hello HTTP/1.1
Content-Type: application/json
x-env: dev


### parse couponfollow
GET {{BASE_URL}}/api/queues/get-by-batch-size?type=download&batchSize=10 HTTP/1.1
Content-Type: application/json
x-env: dev

### parse couponfollow
POST {{BASE_URL}}/api/queues/add HTTP/1.1
Content-Type: application/json
x-env: download-prod

{
    "type": "download",
    "data": {
        "coupon": "1222223",
        "follow": "133323"
    }
}

### bulk add
POST {{BASE_URL}}/api/queues/bulk-add HTTP/1.1
Content-Type: application/json
x-env: dev

{
    "type": "download",
    "data": [
        {
            "coupon": "12311x1xxx",
            "follow": "123"
        },
        {
            "coupon": "12333233",
            "follow": "1234"
        }
    ]
}

### delete
DELETE {{BASE_URL}}/api/queues/0352cd10b8f21c99c497f1a3ef1e6250 HTTP/1.1
Content-Type: application/json
x-env: dev


### update status
PUT {{BASE_URL}}/api/queues/a2c2d558269f48b18e1c36dbc38c8eb3/status HTTP/1.1
Content-Type: application/json
x-env: dev

{
    "status": "fail"
}


### update data
PUT {{BASE_URL}}/api/queues/a2c2d558269f48b18e1c36dbc38c8eb3 HTTP/1.1
Content-Type: application/json
x-env: dev

{
    "status": "fail",
    "errorTimes": 1,
    "result": "error"
}