
### hello
GET {{BASE_URL}}/api/hello HTTP/1.1
Content-Type: application/json
x-env: dev


### parse couponfollow
GET {{BASE_URL}}/api/queues/get-by-batch-size HTTP/1.1
Content-Type: application/json
x-env: dev

### parse couponfollow
POST {{BASE_URL}}/api/queues/add HTTP/1.1
Content-Type: application/json
x-env: dev

{
    "type": "download",
    "data": {
        "coupon": "123",
        "follow": "123"
    }
}

### bulk add
POST {{BASE_URL}}/api/queues/bulk-add HTTP/1.1
Content-Type: application/json
x-env: dev

{
    "type": "download",
    "data": [
        {
            "coupon": "12311x1",
            "follow": "123"
        },
        {
            "coupon": "12333233",
            "follow": "123"
        }
    ]
}

